### ISSUE TITLE
Kernel panic in siw_try_1seg when running ib_send_lat from perftest package

### ISSUE THREAD

**Issue by patrickmacarthur** [zrlio/softiwarp#2] opened 2016-06-15 16:23 UTC
On the latest master (commit id 6731fa60c32c9d4a73a27e0737a4fc99fe48d7c4) running under Linux 3.17.8 (also reproduced under 4.5.7 and 4.6.2, although softiwarp requires patching to run under these versions).

Relevant dmesg:

```
[  519.463509] BUG: unable to handle kernel paging request at 0000000001d39d00
[  519.463577] IP: [<ffffffff8130f096>] memcpy+0x6/0x110
[  519.463629] PGD 84dcf7067 PUD 84fd0a067 PMD 8511b3067 PTE 80000008180d1067
[  519.463697] Oops: 0001 [#1] SMP 
[  519.463732] Modules linked in: siw(OE) xprtrdma ib_isert iscsi_target_mod ib_iser libiscsi scsi_transport_iscsi ib_srpt target_core_mod ib_srp scsi_transport_srp ib_ipoib rdma_ucm ib_ucm ib_uverbs ib_umad rdma_cm ib_cm iw_cm ib_sa ib_mad ib_core ib_addr rpcsec_gss_krb5 nfsv4 dns_resolver nfs fscache x86_pkg_temp_thermal coretemp kvm_intel nfsd kvm crc32_pclmul ghash_clmulni_intel aesni_intel lrw gf128mul glue_helper ablk_helper cryptd auth_rpcgss sg iTCO_wdt iTCO_vendor_support pcspkr mei_me nfs_acl mxm_wmi shpchp lockd mei i2c_i801 acpi_pad ipmi_si ipmi_msghandler lpc_ich mfd_core wmi acpi_power_meter sunrpc ip_tables ext4 mbcache jbd2 sd_mod crc_t10dif crct10dif_generic ast syscopyarea sysfillrect i40e sysimgblt drm_kms_helper ttm drm igb ahci libahci vxlan libata crct10dif_pclmul crct10dif_common
[  519.464528]  udp_tunnel crc32c_intel nvme ptp dca i2c_algo_bit pps_core i2c_core
[  519.464605] CPU: 9 PID: 17376 Comm: ib_send_lat Tainted: G           OE  3.17.8 #1
[  519.464665] Hardware name: Supermicro SYS-6028R-T/X10DRi, BIOS 2.0 12/28/2015
[  519.464721] task: ffff88084ea6a8b0 ti: ffff880852aec000 task.ti: ffff880852aec000
```

Stack trace from crash utility:

```
PID: 17376  TASK: ffff88084ea6a8b0  CPU: 9   COMMAND: "ib_send_lat"
 #0 [ffff880852aef8b0] machine_kexec at ffffffff81052d4b
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/arch/x86/kernel/machine_kexec_64.c: 319
 #1 [ffff880852aef910] crash_kexec at ffffffff81100bd2
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/kernel/kexec.c: 1482
 #2 [ffff880852aef9e0] oops_end at ffffffff810178c8
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/arch/x86/kernel/dumpstack.c: 231
 #3 [ffff880852aefa08] no_context at ffffffff81653748
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/arch/x86/mm/fault.c: 727
 #4 [ffff880852aefa60] __bad_area_nosemaphore at ffffffff81653833
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/arch/x86/mm/fault.c: 807
 #5 [ffff880852aefaa8] bad_area_nosemaphore at ffffffff8165399d
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/arch/x86/mm/fault.c: 815
 #6 [ffff880852aefab8] __do_page_fault at ffffffff810609ef
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/arch/x86/mm/fault.c: 1266
 #7 [ffff880852aefbc0] do_page_fault at ffffffff81060ec1
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/arch/x86/mm/fault.c: 1284
 #8 [ffff880852aefbf0] page_fault at ffffffff81664ba8
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/arch/x86/kernel/entry_64.S: 1268
    [exception RIP: memcpy+6]
    RIP: ffffffff8130f096  RSP: ffff880852aefca0  RFLAGS: 00010206
    RAX: ffff88084db851f4  RBX: ffff88084db851e0  RCX: 0000000000000010
    RDX: 0000000000000010  RSI: 0000000001d39d00  RDI: ffff88084db851f4
    RBP: ffff880852aefce0   R8: 00007ffffffff000   R9: 0000000001d3ad00
    R10: ffff88084c813f00  R11: ffff88104637a100  R12: 0000000000000010
    R13: ffff88084c813f00  R14: ffff88084db85278  R15: ffff88084db85000
    ORIG_RAX: ffffffffffffffff  CS: 0010  SS: 0018
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/arch/x86/lib/memcpy_64.S: 61
 #9 [ffff880852aefca0] siw_try_1seg at ffffffffa076f88f [siw]
    /home/pmacarth/src/softiwarp/kernel/siw_qp_tx.c: 109
#10 [ffff880852aefce8] siw_qp_sq_process at ffffffffa0770eb4 [siw]
    /home/pmacarth/src/softiwarp/kernel/siw_qp_tx.c: 261
#11 [ffff880852aefd80] siw_post_send at ffffffffa076b8c3 [siw]
    /home/pmacarth/src/softiwarp/kernel/siw_verbs.c: 1197
#12 [ffff880852aefdd0] ib_uverbs_post_send at ffffffffa04c4c8c [ib_uverbs]
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/drivers/infiniband/core/uverbs_cmd.c: 2268
#13 [ffff880852aefe68] ib_uverbs_write at ffffffffa04bf1f5 [ib_uverbs]
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/drivers/infiniband/core/uverbs_main.c: 708
#14 [ffff880852aefef8] vfs_write at ffffffff811ec567
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/fs/read_write.c: 532
#15 [ffff880852aeff38] sys_write at ffffffff811ed185
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/fs/read_write.c: 584
#16 [ffff880852aeff80] system_call_fastpath at ffffffff81662c69
    /opt/local-scratch/pmacarth/rpmbuild/BUILD/kernel-3.17.8/arch/x86/kernel/entry_64.S: 423
    RIP: 00007fba8f92b9e0  RSP: 00007fff750d9c50  RFLAGS: 00010206
    RAX: 0000000000000001  RBX: ffffffff81662c69  RCX: 0000000001d39d00
    RDX: 0000000000000020  RSI: 00007fff750d9ef0  RDI: 0000000000000006
    RBP: 0000000000000000   R8: 0000000000000000   R9: 00000000000043e0
    R10: 0000000000000017  R11: 0000000000000246  R12: 00007fba90756000
    R13: 0000000000000000  R14: 0000000001d3ad10  R15: 0000000000000000
    ORIG_RAX: 0000000000000001  CS: 0033  SS: 002b
```

**Comment by BernardMetzler** [comment] 2016-06-17 14:22
Hi Patrick, thanks! I was unable to reproduce so far, but pushed a small fix around there. What version of ib_send_lat are you using?

**Comment by patrickmacarthur** [comment] 2016-06-17 14:47
That appears to have fixed it.

I am using perftest from the RHEL 7.2 repository (perftest-2.4-1.el7.x86_64).

**Comment by BernardMetzler** [comment] 2016-06-17 15:17
great! I'll close it. thanks.

**Closed as completed by BernardMetzler** 2016-06-17 15:17 UTC
